img = imread('../原始、加密、解密图片/lena/lena.png','png');
img1 = imread('../原始、加密、解密图片/辣椒/peppers.png','png');
img2 = imread('../原始、加密、解密图片/狒狒/baboon.png','png');
img3 = imread('../原始、加密、解密图片/飞机/airplane.png','png');
img4 = imread('../原始、加密、解密图片/4.1.05房子/4.1.05.tiff','tiff');
img5 = imread('../原始、加密、解密图片/4.2.06小船/4.2.06.tiff','tiff');
img6 = imread('../原始、加密、解密图片/汽车/house.tiff','tiff');
i = imresize(img,[256,256]);
i1 = imresize(img1,[256,256]);
i2 = imresize(img2,[256,256]);
i3 = imresize(img3,[256,256]);
i4 = imresize(img4,[256,256]);
i5 = imresize(img5,[256,256]);
i6 = imresize(img6,[256,256]);
imwrite(i,'../修改图片/修改后的lena.png','png');
imwrite(i1,'../修改图片/修改后的peppers.png','png');
imwrite(i2,'../修改图片/修改后的baboon.png','png');
imwrite(i3,'../修改图片/修改后的airplane.png','png');
imwrite(i4,'../修改图片/修改后的4.1.05.tiff','tiff');
imwrite(i5,'../修改图片/修改后的4.2.06.tiff','tiff');
imwrite(i6,'../修改图片/修改后的house.tiff','tiff');